//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Presentation.ServicoTipoDesconto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDesconto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoDesconto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desconto {
            get {
                return this.DescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescontoField, value) != true)) {
                    this.DescontoField = value;
                    this.RaisePropertyChanged("Desconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoTipoDesconto.TipoDescontoSoap")]
    public interface TipoDescontoSoap {
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        SW.Presentation.ServicoTipoDesconto.ListarResponse Listar(SW.Presentation.ServicoTipoDesconto.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Presentation.ServicoTipoDesconto.ListarResponse> ListarAsync(SW.Presentation.ServicoTipoDesconto.ListarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoTipoDesconto.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(SW.Presentation.ServicoTipoDesconto.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoTipoDesconto.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(SW.Presentation.ServicoTipoDesconto.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Presentation.ServicoTipoDesconto.TipoDesconto[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(SW.Presentation.ServicoTipoDesconto.TipoDesconto[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoDescontoSoapChannel : SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoDescontoSoapClient : System.ServiceModel.ClientBase<SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap>, SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap {
        
        public TipoDescontoSoapClient() {
        }
        
        public TipoDescontoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoDescontoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDescontoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDescontoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Presentation.ServicoTipoDesconto.ListarResponse SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap.Listar(SW.Presentation.ServicoTipoDesconto.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public SW.Presentation.ServicoTipoDesconto.TipoDesconto[] Listar() {
            SW.Presentation.ServicoTipoDesconto.ListarRequest inValue = new SW.Presentation.ServicoTipoDesconto.ListarRequest();
            inValue.Body = new SW.Presentation.ServicoTipoDesconto.ListarRequestBody();
            SW.Presentation.ServicoTipoDesconto.ListarResponse retVal = ((SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Presentation.ServicoTipoDesconto.ListarResponse> SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap.ListarAsync(SW.Presentation.ServicoTipoDesconto.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Presentation.ServicoTipoDesconto.ListarResponse> ListarAsync() {
            SW.Presentation.ServicoTipoDesconto.ListarRequest inValue = new SW.Presentation.ServicoTipoDesconto.ListarRequest();
            inValue.Body = new SW.Presentation.ServicoTipoDesconto.ListarRequestBody();
            return ((SW.Presentation.ServicoTipoDesconto.TipoDescontoSoap)(this)).ListarAsync(inValue);
        }
    }
}
