//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Presentation.ServicoProdutoPromocao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoPromocao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProdutoPromocao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int ProdutoIdField;
        
        private int PromocaoIdField;
        
        private bool AtivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SW.Presentation.ServicoProdutoPromocao.Promocao PromocaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SW.Presentation.ServicoProdutoPromocao.Produto ProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PromocaoId {
            get {
                return this.PromocaoIdField;
            }
            set {
                if ((this.PromocaoIdField.Equals(value) != true)) {
                    this.PromocaoIdField = value;
                    this.RaisePropertyChanged("PromocaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Ativa {
            get {
                return this.AtivaField;
            }
            set {
                if ((this.AtivaField.Equals(value) != true)) {
                    this.AtivaField = value;
                    this.RaisePropertyChanged("Ativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SW.Presentation.ServicoProdutoPromocao.Promocao Promocao {
            get {
                return this.PromocaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocaoField, value) != true)) {
                    this.PromocaoField = value;
                    this.RaisePropertyChanged("Promocao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SW.Presentation.ServicoProdutoPromocao.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promocao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Promocao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        private double ValorField;
        
        private int TipoDescontoIdField;
        
        private int QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SW.Presentation.ServicoProdutoPromocao.TipoDesconto TipoDescontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TipoDescontoId {
            get {
                return this.TipoDescontoIdField;
            }
            set {
                if ((this.TipoDescontoIdField.Equals(value) != true)) {
                    this.TipoDescontoIdField = value;
                    this.RaisePropertyChanged("TipoDescontoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SW.Presentation.ServicoProdutoPromocao.TipoDesconto TipoDesconto {
            get {
                return this.TipoDescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDescontoField, value) != true)) {
                    this.TipoDescontoField = value;
                    this.RaisePropertyChanged("TipoDesconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private double PrecoField;
        
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao ProdutoPromocaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao ProdutoPromocao {
            get {
                return this.ProdutoPromocaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoPromocaoField, value) != true)) {
                    this.ProdutoPromocaoField = value;
                    this.RaisePropertyChanged("ProdutoPromocao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDesconto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoDesconto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desconto {
            get {
                return this.DescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescontoField, value) != true)) {
                    this.DescontoField = value;
                    this.RaisePropertyChanged("Desconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoProdutoPromocao.ProdutoPromocaoSoap")]
    public interface ProdutoPromocaoSoap {
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        SW.Presentation.ServicoProdutoPromocao.ListarResponse Listar(SW.Presentation.ServicoProdutoPromocao.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarResponse> ListarAsync(SW.Presentation.ServicoProdutoPromocao.ListarRequest request);
        
        // CODEGEN: Generating message contract since element name ListarPorIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPorId", ReplyAction="*")]
        SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse ListarPorId(SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse> ListarPorIdAsync(SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        void Excluir(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirPorIdProduto", ReplyAction="*")]
        void ExcluirPorIdProduto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirPorIdProduto", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirPorIdProdutoAsync(int id);
        
        // CODEGEN: Generating message contract since element name produtoPromocao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        SW.Presentation.ServicoProdutoPromocao.CadastrarResponse Cadastrar(SW.Presentation.ServicoProdutoPromocao.CadastrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.CadastrarResponse> CadastrarAsync(SW.Presentation.ServicoProdutoPromocao.CadastrarRequest request);
        
        // CODEGEN: Generating message contract since element name produtoPromocao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        SW.Presentation.ServicoProdutoPromocao.AtualizarResponse Atualizar(SW.Presentation.ServicoProdutoPromocao.AtualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.AtualizarResponse> AtualizarAsync(SW.Presentation.ServicoProdutoPromocao.AtualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(SW.Presentation.ServicoProdutoPromocao.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(SW.Presentation.ServicoProdutoPromocao.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPorId", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequestBody Body;
        
        public ListarPorIdRequest() {
        }
        
        public ListarPorIdRequest(SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ListarPorIdRequestBody() {
        }
        
        public ListarPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponseBody Body;
        
        public ListarPorIdResponse() {
        }
        
        public ListarPorIdResponse(SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao ListarPorIdResult;
        
        public ListarPorIdResponseBody() {
        }
        
        public ListarPorIdResponseBody(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao ListarPorIdResult) {
            this.ListarPorIdResult = ListarPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cadastrar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.CadastrarRequestBody Body;
        
        public CadastrarRequest() {
        }
        
        public CadastrarRequest(SW.Presentation.ServicoProdutoPromocao.CadastrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao;
        
        public CadastrarRequestBody() {
        }
        
        public CadastrarRequestBody(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            this.produtoPromocao = produtoPromocao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.CadastrarResponseBody Body;
        
        public CadastrarResponse() {
        }
        
        public CadastrarResponse(SW.Presentation.ServicoProdutoPromocao.CadastrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CadastrarResponseBody {
        
        public CadastrarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Atualizar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.AtualizarRequestBody Body;
        
        public AtualizarRequest() {
        }
        
        public AtualizarRequest(SW.Presentation.ServicoProdutoPromocao.AtualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao;
        
        public AtualizarRequestBody() {
        }
        
        public AtualizarRequestBody(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            this.produtoPromocao = produtoPromocao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Presentation.ServicoProdutoPromocao.AtualizarResponseBody Body;
        
        public AtualizarResponse() {
        }
        
        public AtualizarResponse(SW.Presentation.ServicoProdutoPromocao.AtualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AtualizarResponseBody {
        
        public AtualizarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdutoPromocaoSoapChannel : SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoPromocaoSoapClient : System.ServiceModel.ClientBase<SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap>, SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap {
        
        public ProdutoPromocaoSoapClient() {
        }
        
        public ProdutoPromocaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoPromocaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoPromocaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoPromocaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Presentation.ServicoProdutoPromocao.ListarResponse SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.Listar(SW.Presentation.ServicoProdutoPromocao.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao[] Listar() {
            SW.Presentation.ServicoProdutoPromocao.ListarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.ListarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.ListarRequestBody();
            SW.Presentation.ServicoProdutoPromocao.ListarResponse retVal = ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarResponse> SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.ListarAsync(SW.Presentation.ServicoProdutoPromocao.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarResponse> ListarAsync() {
            SW.Presentation.ServicoProdutoPromocao.ListarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.ListarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.ListarRequestBody();
            return ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).ListarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.ListarPorId(SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest request) {
            return base.Channel.ListarPorId(request);
        }
        
        public SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao ListarPorId(int id) {
            SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest inValue = new SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequestBody();
            inValue.Body.id = id;
            SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse retVal = ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).ListarPorId(inValue);
            return retVal.Body.ListarPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse> SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.ListarPorIdAsync(SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest request) {
            return base.Channel.ListarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.ListarPorIdResponse> ListarPorIdAsync(int id) {
            SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest inValue = new SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.ListarPorIdRequestBody();
            inValue.Body.id = id;
            return ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).ListarPorIdAsync(inValue);
        }
        
        public void Excluir(int id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(int id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public void ExcluirPorIdProduto(int id) {
            base.Channel.ExcluirPorIdProduto(id);
        }
        
        public System.Threading.Tasks.Task ExcluirPorIdProdutoAsync(int id) {
            return base.Channel.ExcluirPorIdProdutoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Presentation.ServicoProdutoPromocao.CadastrarResponse SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.Cadastrar(SW.Presentation.ServicoProdutoPromocao.CadastrarRequest request) {
            return base.Channel.Cadastrar(request);
        }
        
        public void Cadastrar(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            SW.Presentation.ServicoProdutoPromocao.CadastrarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.CadastrarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.CadastrarRequestBody();
            inValue.Body.produtoPromocao = produtoPromocao;
            SW.Presentation.ServicoProdutoPromocao.CadastrarResponse retVal = ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).Cadastrar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.CadastrarResponse> SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.CadastrarAsync(SW.Presentation.ServicoProdutoPromocao.CadastrarRequest request) {
            return base.Channel.CadastrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.CadastrarResponse> CadastrarAsync(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            SW.Presentation.ServicoProdutoPromocao.CadastrarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.CadastrarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.CadastrarRequestBody();
            inValue.Body.produtoPromocao = produtoPromocao;
            return ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).CadastrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Presentation.ServicoProdutoPromocao.AtualizarResponse SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.Atualizar(SW.Presentation.ServicoProdutoPromocao.AtualizarRequest request) {
            return base.Channel.Atualizar(request);
        }
        
        public void Atualizar(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            SW.Presentation.ServicoProdutoPromocao.AtualizarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.AtualizarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.AtualizarRequestBody();
            inValue.Body.produtoPromocao = produtoPromocao;
            SW.Presentation.ServicoProdutoPromocao.AtualizarResponse retVal = ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).Atualizar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.AtualizarResponse> SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap.AtualizarAsync(SW.Presentation.ServicoProdutoPromocao.AtualizarRequest request) {
            return base.Channel.AtualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Presentation.ServicoProdutoPromocao.AtualizarResponse> AtualizarAsync(SW.Presentation.ServicoProdutoPromocao.ProdutoPromocao produtoPromocao) {
            SW.Presentation.ServicoProdutoPromocao.AtualizarRequest inValue = new SW.Presentation.ServicoProdutoPromocao.AtualizarRequest();
            inValue.Body = new SW.Presentation.ServicoProdutoPromocao.AtualizarRequestBody();
            inValue.Body.produtoPromocao = produtoPromocao;
            return ((SW.Presentation.ServicoProdutoPromocao.ProdutoPromocaoSoap)(this)).AtualizarAsync(inValue);
        }
    }
}
